#!/bin/bash -l

#SBATCH
#SBATCH --job-name=binannot
#SBATCH --time=12:0:0
#SBATCH --partition=defq
#SBATCH --nodes=1
# number of tasks (processes) per node
#SBATCH --ntasks-per-node=1
# number of cpus (threads) per task (process)

#### load and unload modules you may need
# module unload openmpi/intel
# module load mvapich2/gcc/64/2.0b
# module list
#module load bowtie2
#module load python/2.7
module load samtools
#module list


#### parsing arguments
OPTIND=1
while getopts f:x:w:s::o:b:c: option  
do                                                                                                                           
  case "${option}"                                                                                                         
  in
      f) fname=$OPTARG ;;
      x) refname=$OPTARG ;;
      w) binsize=$OPTARG ;;
      s) binstep=$OPTARG ;;
      o) outfname=$OPTARG ;;

      b)  set -f
	  IFS=','
	  bsfiles=($OPTARG) ;;

      c)  set -f
	  IFS=','
	  chipfiles=($OPTARG) ;;
            
  esac                                                                                                                       
done
set +o noglob
#set +f

echo
echo Submitted
echo "fname $fname"
echo "bsfiles ${bsfiles[@]}"
echo "chipfiles ${chipfiles[@]}"
echo "refname $refname"
echo "binsize $binsize"
echo "binstep $binstep"
echo "outfname $outfname"


#python data/scripts/bincount.py ${files[1]} ${files[2]} ${files[3]} ${files[4]} ${files[5]} ${files[6]} ${files[7]} ${files[0]} work/condense_seq/hg19.fa -o $outfname -w 1000 --gc

#python data/scripts/bincount.py ${files[1]} ${files[2]} ${files[3]} ${files[4]} ${files[5]} ${files[6]} ${files[7]} ${files[0]} $refname -o $outfname -w 1000 --gc

#python work/scripts/bincount.py ${files[1]} ${files[2]} ${files[3]} ${files[4]} ${files[5]} ${files[0]} ${refname} -o ${outfname} -w ${winsize} --gc

#python work/scripts/combine_annot_edit.py ${fname} ${refname} --chip ${chipnames[1]} ${chipfiles[1]} ${chipnames[2]} ${chipfiles[2]} ${chipnames[3]} ${chipfiles[3]} ${chipnames[4]} ${chipfiles[4]} ${chipnames[5]} ${chipfiles[5]} ${chipnames[6]} ${chipfiles[6]} ${chipnames[7]} ${chipfiles[7]} ${chipnames[8]} ${chipfiles[8]} --Bin ${binsize} ${binstep}

#python2 /home/spark159/scratch4-tha4/sangwoo/scripts/combine_annot_edit.py ${fname} ${refname} --bs ${bsfiles[*]} --chip ${chipfiles[*]} --Bin ${binsize} ${binstep} --chr chr1 -o ${outfname}

python2 /home/spark159/scratch4-tha4/sangwoo/scripts/combine_annot_edit.py ${fname} ${refname} --Bin ${binsize} ${binstep} --chr chr1 -o ${outfname}

#python work/scripts/combine_annot_edit.py ${fname} ${refname} --chip ${chipfiles[*]} --Bin ${binsize} ${binstep} --chr chr1 -o ${outfname}

#python work/scripts/combine_annot_edit.py ${fname} ${refname} --Bin ${binsize} ${binstep} --chr chr1 -o ${outfname}


#path="work/2021_02_10_H1_sp_spd_test/"

#cells=('H1')
#stypes=('DNA' 'NCP-new')
#agents=('sp' 'spd')

#for cell in ${cells[*]}
#do
#    for stype in ${stypes[*]}
#    do
#	for agent in ${agents[*]}
#	do
#	    fname="${path}${cell}_${stype}_${agent}_10kb.cn"
#	    outfname="${path}${cell}_${stype}_${agent}_10kb"
#	    echo $fname
#	    python work/scripts/combine_annot_edit.py ${fname} "${path}hg19.fa" --chip H2AZ "${path}H2AZ.bedGraph" H3k27ac "${path}H3k27ac.bedGraph" H3k27me3 "${path}H3k27me3.bedGraph" H3k36me3 "${path}H3k36me3.bedGraph" H3k4me1 "${path}H3k4me1.bedGraph" H3k4me3 "${path}H3k4me3.bedGraph" H3k9ac "${path}H3k9ac.bedGraph" H3k9me3 "${path}H3k9me3.bedGraph" --Bin 10000 10000 --chr chr1 -o ${outfname}
#	    #echo $outfname
#	    echo
#	    echo
#	done
#    done
#done


echo "Finished with job $SLURM_JOBID"
echo
