#!/bin/bash -l

#SBATCH
#SBATCH --job-name=bincount
#SBATCH --time=12:0:0
#SBATCH --partition=defq
#SBATCH --nodes=1
# number of tasks (processes) per node
#SBATCH --ntasks-per-node=5
# number of cpus (threads) per task (process)

#### load and unload modules you may need
# module unload openmpi/intel
# module load mvapich2/gcc/64/2.0b
# module list
#module load bowtie2
#module load python/2.7
module load samtools
#module list


#### parsing arguments
OPTIND=1
while getopts f:t:c:g:o option  
do                                                                                                                           
  case "${option}"                                                                                                         
  in
      f)  set -f
          IFS=','
          files=($OPTARG) ;;

      t)  set -f
          IFS=','
          tnums=($OPTARG) ;;

      c)  set -f
          IFS=','
          chr_list=($OPTARG) ;;

      g) tfname=$OPTARG ;;
      m) min_rsq=$OPTARG ;;
      o) outfname=$OPTARG ;;
      
  esac                                                                                                                       
done
set +o noglob

echo ${files[@]}
echo ${tfname}
echo ${tnums}
echo ${min_rsq}
echo

python2 /home/spark159/scratch/scripts/get_Chalf.py ${files[*]} -t ${tfname} --tnum ${tnums} --chr ${chr_list[*]} --min_rsq ${min_rsq} -o ${outfname}

echo "Finished with job $SLURM_JOBID"
