#!/bin/bash -l

#SBATCH
#SBATCH --job-name=bowtie
#SBATCH --time=24:0:0
#SBATCH --partition=defq
#SBATCH --nodes=1
# number of tasks (processes) per node
#SBATCH --ntasks-per-node=3
# number of cpus (threads) per task (process)
#SBATCH --mail-type=end
#SBATCH --mail-user=spark159@jhu.edu

#### load and unload modules you may need
# module unload openmpi/intel
# module load mvapich2/gcc/64/2.0b
# module list
module load samtools
#module list

#### parsing arguments
OPTIND=1
while getopts i:o: option  
do                                                                                                                           
  case "${option}"                                                                                                         
  in
      i) input_filename=$OPTARG ;;

      o) output_filename=$OPTARG ;;

  esac                                                                                                                       
done

echo Converting $input_filename
echo

samtools view -S -b -h $input_filename > $output_filename
rm $input_filename
#samtools sort $output_filename -o $output_filename

echo "Finished with job $SLURM_JOBID"
