#!/bin/bash -l

#SBATCH
#SBATCH --job-name=python_code
#SBATCH --time=100:0:0
#SBATCH --partition=parallel
#SBATCH --nodes=1
# number of tasks (processes) per node
#SBATCH --ntasks-per-node=24
# number of cpus (threads) per task (process)
#SBATCH --cpus-per-task=1
#SBATCH --mail-type=end
#SBATCH --mail-user=spark159@jhu.edu

#### load and unload modules you may need
module load bowtie2
module load samtools
#module load python
module load R
#module load python3
module list

python danpos-2.2.2/danpos.py dpos work/condense_seq/sp1_hg19_chr1.bam -m 1
echo "Finished with job $SLURM_JOBID"

#### mpiexec by default launches number of tasks requested
