#!/bin/bash -l
#SBATCH
#SBATCH --job-name=python_code
#SBATCH --time=12:0:0
#SBATCH --partition=defq
#SBATCH --nodes=1
# number of tasks (processes) per node
#SBATCH --ntasks-per-node=3

#### load and unload modules you may need
#module load bowtie2
#module load samtools
#module load python

#module load python/2.7
#module load anaconda
#module load python/3.7.4-anaconda
#module load anaconda
module list

#/home/spark159/juicedir/scripts/juicer.sh -D /home/spark159/juicedir/ -d /home/spark159/juicedir/HIC003 -g hg19
/home/spark159/juicedir/scripts/juicer_edited.sh -D /home/spark159/juicedir/ -d /home/spark159/juicedir/HIC003 -g hg19 -q defq -l defq -Q 12 -L 12



echo "Finished with job $SLURM_JOBID"

#### mpiexec by default launches number of tasks requested
