#!/bin/bash -l

#SBATCH
#SBATCH --job-name=lendist
#SBATCH --time=12:0:0
#SBATCH --partition=defq
#SBATCH --nodes=1
# number of tasks (processes) per node
#SBATCH --ntasks-per-node=1
# number of cpus (threads) per task (process)

#### load and unload modules you may need
# module unload openmpi/intel
# module load mvapich2/gcc/64/2.0b
# module list
#module load bowtie2
#module load python/2.7
module load samtools
#module list


#### parsing arguments
OPTIND=1
while getopts f:o: option  
do                                                                                                                           
  case "${option}"                                                                                                         
  in
      f)  set -f
          IFS=','
          files=($OPTARG) ;;

      o) outfname=$OPTARG ;;
      
  esac                                                                                                                       
done
set +o noglob

echo Submitted $outfname
echo ${files[@]}
echo

python2 /home/spark159/scratch/scripts/lendist.py ${files[*]} -o ${outfname}

echo "Finished with job $SLURM_JOBID"
