#!/bin/bash -l

#SBATCH
#SBATCH --job-name=NCPcov
#SBATCH --time=24:00:00
#SBATCH --partition=parallel
#SBATCH --nodes=1
# number of tasks (processes) per node
#SBATCH --ntasks-per-node=10
# number of cpus (threads) per task (process)

#### load and unload modules you may need
#module load bowtie2
module load samtools
#module load python
#module load python/2.7
#module load samtools/1.15.1
#module load samtools/1.15.1-multiple_instances
module list


#### parsing arguments
OPTIND=1
while getopts f:g:n:c:o: option  
do                                                                                                                           
  case "${option}"                                                                                                         
  in
      f) peak_fname=$OPTARG ;;
      g) cov_fname=$OPTARG ;;
      n) Nlen=$OPTARG ;;
      c) chr_name=$OPTARG ;;
      o) outfname=$OPTARG ;;
      
  esac                                                                                                                       
done
set +o noglob

echo Submitted $outfname
echo ${files[@]}
echo

#echo "chr name $chr_name window $win_size"
echo "Producing $outfname files"

#get coverage for each NCP
python2 /home/spark159/scratch/scripts/NCPcov_ver3.py ${peak_fname} ${cov_fname} --Nlen ${Nlen} --peak-choice input --chr ${chr_name} -o ${outfname}
