#!/bin/bash -l

#SBATCH
#SBATCH --job-name=NCPnum
#SBATCH --time=12:0:0
#SBATCH --partition=parallel
#SBATCH --nodes=1
# number of tasks (processes) per node
#SBATCH --ntasks-per-node=5
# number of cpus (threads) per task (process)

#### load and unload modules you may need
# module unload openmpi/intel
# module load mvapich2/gcc/64/2.0b
# module list
#module load bowtie2
#module load python/2.7
module load samtools
#module list


#### parsing arguments
OPTIND=1
while getopts f:c:g:t:i: option  
do                                                                                                                           
  case "${option}"                                                                                                         
  in
      f)  set -f
          IFS=','
          files=($OPTARG) ;;

      c)  set -f
          IFS=','
          chr_list=($OPTARG) ;;

      g) tfname=$OPTARG ;;
      t) tnum=$OPTARG ;;
      i) mscale=$OPTARG;;
      
  esac                                                                                                                       
done
set +o noglob

echo ${files[@]}
echo ${tfname}
echo ${tnum}
echo ${mscale}
echo

python2 /home/spark159/scratch/scripts/NCPnum_ver2.py ${files[*]} -t ${tfname} --tnum ${tnum} --mscale ${mscale} --chr ${chr_list[*]}

echo "Finished with job $SLURM_JOBID"
