#!/bin/bash -l

#SBATCH
#SBATCH --job-name=NCPscore
#SBATCH --time=12:0:0
#SBATCH --partition=parallel
#SBATCH --nodes=1
# number of tasks (processes) per node
#SBATCH --ntasks-per-node=5
# number of cpus (threads) per task (process)

#### load and unload modules you may need
# module unload openmpi/intel
# module load mvapich2/gcc/64/2.0b
# module list
#module load bowtie2
#module load python/2.7
module load samtools
#module list


#### parsing arguments
OPTIND=1
while getopts f:i:g:t:c: option  
do                                                                                                                           
  case "${option}"                                                                                                         
  in
      f)  set -f
          IFS=','
          files=($OPTARG) ;;

      i)  set -f
          IFS=','
          input_files=($OPTARG) ;;

      c)  set -f
          IFS=','
          chr_list=($OPTARG) ;;

      g) tfname=$OPTARG ;;
      t) tnum=$OPTARG ;;
      
  esac                                                                                                                       
done
set +o noglob

echo ${files[@]}
echo ${input_files[@]}
echo

python2 /home/spark159/scratch/scripts/NCPscore_ver4.py ${files[*]} -i ${input_files[*]} -t ${tfname} --tnum ${tnum} --chr ${chr_list[*]} --numc

echo "Finished with job $SLURM_JOBID"
