#!/bin/bash -l

#SBATCH
#SBATCH --job-name=occupancy
#SBATCH --time=12:00:00
#SBATCH --partition=defq
#SBATCH --nodes=1
# number of tasks (processes) per node
#SBATCH --ntasks-per-node=20
#SBATCH --mem-per-cpu=4GB
# number of cpus (threads) per task (process)

#### load and unload modules you may need
#module load bowtie2
module load samtools
#module load python
#module load python/2.7
module list


#### parsing arguments
OPTIND=1
while getopts f:x:b:s:c:o: option  
do                                                                                                                           
  case "${option}"                                                                                                         
  in
      f)  set -f
          IFS=','
          files=($OPTARG) ;;

      x) refname=$OPTARG ;;
      b) binsize=$OPTARG ;;
      s) binstep=$OPTARG ;;
      c) chr_name=$OPTARG ;;
      o) outfname=$OPTARG ;;
      
  esac                                                                                                                       
done
set +o noglob

echo Submitted $outfname
echo ${files[@]}
echo


#echo "chr name $chr_name window $win_size"
echo "Producing $outfname files"

#get nucleosome occupancy along the genome
python2 /home/spark159/scratch/scripts/occupancy_edit.py ${files[*]} ${refname} --skip --chr ${chr_name} -o ${outfname}

echo "Finished with job $SLURM_JOBID"

#### mpiexec by default launches number of tasks requested
