#!/bin/bash -l

#SBATCH
#SBATCH --job-name=read_qc
#SBATCH --time=24:0:0
#SBATCH --partition=shared
#SBATCH --nodes=1
# number of tasks (processes) per node
#SBATCH --ntasks-per-node=5
# number of cpus (threads) per task (process)
#SBATCH --mail-type=end
#SBATCH --mail-user=spark159@jhu.edu

#### load and unload modules you may need
# module unload openmpi/intel
# module load mvapich2/gcc/64/2.0b
# module list
#module load bowtie2
#module load samtools
#module list

#### parsing arguments
OPTIND=1
while getopts f:g:o: option  
do                                                                                                                           
  case "${option}"                                                                                                         
  in
      f)  set -f
          IFS=','
          files=($OPTARG) ;;
      
      o) outfname=$OPTARG ;;

  esac                                                                                                                       
done
set +o noglob

echo Submitted $outfname
echo ${files[@]}
echo

#python data/scripts/read_qc.py ${files[0]} ${files[1]} ${files[2]} ${files[3]} -o $outfname
python data/scripts/read_qc.py ${files[0]} ${files[1]} -o $outfname
#python data/scripts/read_qc.py ${files[0]} -o $outfname


echo "Finished with job $SLURM_JOBID"
