#!/bin/bash -l

#SBATCH
#SBATCH --job-name=rgs
#SBATCH --time=24:0:0
#SBATCH --partition=shared
#SBATCH --nodes=1
# number of tasks (processes) per node
#SBATCH --ntasks-per-node=3
# number of cpus (threads) per task (process)
#SBATCH --mail-type=end
#SBATCH --mail-user=spark159@jhu.edu

#### load and unload modules you may need
# module unload openmpi/intel
# module load mvapich2/gcc/64/2.0b
# module list
#module load bowtie2
#module load samtools
#module list

#### parsing arguments
OPTIND=1
while getopts f:g:o: option  
do                                                                                                                           
  case "${option}"                                                                                                         
  in
      f) infname=$OPTARG ;;
      
      o) outfname=$OPTARG ;;

  esac                                                                                                                       
done

echo Submitted $infname
echo

python data/scripts/rgs_submit.py $infname --bethe -o $outfname --cycle 10000000 --replica 10 --max-root 100 --sigma 1

echo "Finished with job $SLURM_JOBID"
