#!/bin/bash -l

#SBATCH
#SBATCH --job-name=slide_sort
#SBATCH --time=24:00:00
#SBATCH --partition=defq
#SBATCH --nodes=1
# number of tasks (processes) per node
#SBATCH --ntasks-per-node=3
# number of cpus (threads) per task (process)

#### load and unload modules you may need
# module unload openmpi/intel
# module load mvapich2/gcc/64/2.0b
# module list
module load bowtie2
module load samtools
#module list
#module load cutadapt

#### parsing arguments
OPTIND=1
while getopts f:g:x:o:m: option  
do                                                                                                                           
  case "${option}"                                                                                                         
  in

      f) infname1=$OPTARG ;;

      g) infname2=$OPTARG ;;

      x) refname=$OPTARG ;;

      o) outfname=$OPTARG ;;

      m) sortmode=$OPTARG ;;

  esac                                                                                                                       
done

echo $infname1
echo $infname2
echo $outfname
echo $sortmode

path="/home/spark159/scratch/scripts/"

python2 ${path}sort_final.py ${infname1} ${infname2} ${refname} -o ${outfname} --dw

    

echo "Finished with job $SLURM_JOBID"
